[package]
name = "rust-if-else"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/app-if-else.rs"
name = "rustifelse"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
